### ISSUE TITLE
INP to STL conversion 

### ISSUE THREAD

**Issue by RBehera87** [effepivi/inp2stl#2]
Hi,

I have an Abaqus .inp file with hexahedral mesh (Element type=C3D8). Can I convert it to STL?
I tried but it says Number of meshes in data.inp :  0

Any help? 

Thanks,
Rajdeep

**Comment by effepivi** [comment]
Hi Rajdeep,

you may have to tweak the script. INP files can be a pain, with different codes.
Can you share your file?

regards,
Franck

**Comment by luye3** [comment]
Hi，
I'm a newbie to code.I want to learn gvxr-demos，but now i follow your Readme，a lot of operations can‘t be done.How do i go about learning your gvxr demos?


Thanks

**Comment by effepivi** [comment]
Hi,

in this case, please open an issue in the right repository and please be more specific with the issue you have.
I'll close this issue as the previous person did not follow up and your new request is not related to this repository.

regards
